In [8]:
# Khai báo một mảng numpy hai chiều A mô tả ma trận:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# Với một số tự nhiên n, 
# hãy viết hàm trả về ma trận có dạng đường chéo phụ ngay dưới đường chéo chính nhận các giá trị từ 1 đến n. 
# Các thành phần là kiểu số nguyên.
import numpy as np
n = 5 
np.diag([x for x in range(1, n+1)], k=-1)

array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0]])

In [13]:
# Cho một ma trận A, 
# viết hàm myfunc tính tổng các phần tử trên các cột có chỉ số chẵn (0, 2, 4, ...) của ma trận đó. 
import numpy as np
A = np.array([[1, 2, 10], [3, 5, 6], [7, 8, 9]])
def myfunc(A):
    kt = A.shape[1]
    s = 0
    for i in range(0, kt, 2):
        s += np.sum(A[:, i])
    return s
print(myfunc(A))

36


In [18]:
# Viết hàm myfunc tính tổng tất cả các phần tử có cả hai chỉ số đều chẵn của một ma trận A bất kỳ.

import numpy as np
A = np.array([[1, 2, 10], [3, 5, 6], [7, 8, 9]])

def myfunc(A):
    kt = A.shape[1]
    s = 0
    for i in range(0, kt, 2):
        for j in range(0, kt, 2):
            s += np.sum(A[j, i])
    return s
print(A)
print(myfunc(A))


[[ 1  2 10]
 [ 3  5  6]
 [ 7  8  9]]
27


In [19]:
# Cho một ma trận A bất kỳ. 
# Trong mỗi hàng, ta định nghĩa độ biến động của nó là 
# sự khác nhau giữa giá trị lớn nhất và nhỏ nhất của các phần tử trong hàng đó. 
# Hãy viết hàm myfunc trả về tổng độ biến động của tất cả các hàng trong ma trận đó.
# Ví dụ với ma trận A trong bài học, độ biến động của mỗi hàng lần lượt là 2.0, 4.0, 3.0. Vậy myfunc(A) = 9.0.

import numpy as np
A = np.array([[1, 2, 10], [3, 5, 6], [7, 8, 9]])

def myfunc(A):
    s = 0
    for i in range(A.shape[0]):
        s += np.max(A[i]) - np.min(A[i])
    return s
print(myfunc(A))

14


In [21]:
# Frobenius norm của một ma trận được định nghĩa là căn bậc hai của tổng bình phương các phần tử của ma trận. 
# Frobenius norm được sử dụng rất nhiều trong các thuật toán Machine Learning vì các tính chất toán học đẹp 
# của nó, trong đó quan trọng nhất là việc đạo hàm của bình phương của nó rất đơn giản.
# Frobenius norm của một ma trận 

import numpy as np
A = np.array([[1, 2, 10], [3, 5, 6], [7, 8, 9]])
def myfunc(A):
    s = 0
    for i in range(A.shape[0]):
        for j in range(A.shape[0]):
            s += A[i, j]**2
    return np.sqrt(s)
print(myfunc(B))



6.244997998398398
